version: '2.25'
services:
  openai-wechat:
    image: wechat-gptbot:latest
    container_name: wechat-bot
    privileged: true
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./token.json:/code/token.json
    network_mode: bridge
    environment:
      - TZ=Asia/Shanghai
    restart: always
    sysctls:
      net.core.somaxconn: 16384
