[router]
check_login ="/wechat-gptbot/checklogin"
current_models ="/wechat-gptbot/current-model"
reset_model ="/wechat-gptbot/reset-model"
friends ="/wechat-gptbot/friends"
weather_cron_setting="/wechat-gptbot/weather/cron-setting"
weather_receiver="/wechat-gptbot/weather/receiver"
news_receiver="/wechat-gptbot/news/receiver"
news_cron_setting="/wechat-gptbot/news/cron-setting"
sport_cron_setting="/wechat-gptbot/sport/cron-setting"
sport_receiver="/wechat-gptbot/sport/receiver"
reset_cron = "/wechat-gptbot/cron-reset"
reset_rss = "/wechat-gptbot/rss-reset"