[router]
check_login ="/wechat-gptbot/checklogin"
current_models ="/wechat-gptbot/current-model"
reset_model ="/wechat-gptbot/reset-model"
friends ="/wechat-gptbot/friends"
weather_cron_setting="/wechat-gptbot/weather-cron-setting"
weather_receiver="/wechat-gptbot/weather-receiver"